version: 1
validation: sovereign
accounts: 
- name: alice
  coins:
  - 3000000000000ubcna
- name: bob
  coins:
  - 2000000000000ubcna
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 100000ubcna
validators:
- name: alice
  bonded: 100000000ubcna
genesis:
 app_state:
   staking:
     params:
       bond_denom: "ubcna"
   crisis:
     constant_fee:
       denom: "ubcna"
       amount: "1000"
   mint:
     params:
       mint_denom: "ubcna"
   gov:
     params:
       min_deposit:
         - denom: "ubcna"
           amount: "100000"
       voting_period: "300s"
       expedited_min_deposit:
         - denom: "ubcna"
           amount: "100000"
       expedited_voting_period: "100s"
   wasm:
     params:
       code_upload_access:
         addresses: []
         permission: "Nobody"
       instantiate_default_permission: "Nobody"
client:
 vuex:
   path: "vue/src/store"
 openapi:
   path: "docs/static/openapi.yml"
init:
client:
  keyring-backend: test/os